[2025-08-28T06:17:13.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T06:17:13.318+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: contoh_taskgroup_api_santai.siapin_folder manual__2025-08-28T06:17:09.149920+00:00 [queued]>
[2025-08-28T06:17:13.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: contoh_taskgroup_api_santai.siapin_folder manual__2025-08-28T06:17:09.149920+00:00 [queued]>
[2025-08-28T06:17:13.337+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T06:17:13.365+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): siapin_folder> on 2025-08-28 06:17:09.149920+00:00
[2025-08-28T06:17:13.383+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=999) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-28T06:17:13.386+0000] {standard_task_runner.py:63} INFO - Started process 1001 to run task
[2025-08-28T06:17:13.387+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'contoh_taskgroup_api_santai', 'siapin_folder', 'manual__2025-08-28T06:17:09.149920+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpe1utyu64']
[2025-08-28T06:17:13.394+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask siapin_folder
[2025-08-28T06:17:13.526+0000] {task_command.py:426} INFO - Running <TaskInstance: contoh_taskgroup_api_santai.siapin_folder manual__2025-08-28T06:17:09.149920+00:00 [running]> on host 97ae95ca845c
[2025-08-28T06:17:13.734+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='contoh_taskgroup_api_santai' AIRFLOW_CTX_TASK_ID='siapin_folder' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T06:17:09.149920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T06:17:09.149920+00:00'
[2025-08-28T06:17:13.740+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T06:17:13.746+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-28T06:17:13.748+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T06:17:13.768+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=contoh_taskgroup_api_santai, task_id=siapin_folder, run_id=manual__2025-08-28T06:17:09.149920+00:00, execution_date=20250828T061709, start_date=20250828T061713, end_date=20250828T061713
[2025-08-28T06:17:13.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-28T06:17:13.901+0000] {taskinstance.py:3503} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-08-28T06:17:13.910+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
